version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: database

  app:
    build: .
    depends_on:
      - db
    volumes:
      - ./src:/app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:admin@db:5432/database
